name: "Set Assignee"
on:
  issues:
    branches-ignore:
        - '**'
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.github_token }}
          assignees: urapadmin
                     ${{ github.actor }}

